Io.snapcraft.privileged desktop launcher
MirServer/snapd pull request #3
Opened 2020-09-16 10:48 UTC by AlanGriffiths

2020-09-16 11:40 UTC, jhenstridge commented on data/dbus/io.snapcraft.PrivilegedDesktopLauncher.service.in
> +AssumedAppArmorLabel=unconfined
I would strongly recommend against adding another bus name.  Clients should be able to access the new APIs by making calls to the existing `io.snapcraft.Launcher` bus name.

The existing code inside userd conflates bus names with interface names, but I wouldn't exacerbate it by adding more service activation files.

2020-10-12 07:49 UTC, jhenstridge requested changes
A few small changes are needed to work after #9370 was landed, but overall this looks good.

2020-10-12 07:49 UTC, jhenstridge commented on data/dbus/io.snapcraft.PrivilegedDesktopLauncher.service.in
> +AssumedAppArmorLabel=unconfined
With #9370 merged, this file can be removed.

2020-10-12 07:49 UTC, jhenstridge commented on usersession/userd/privileged_desktop_launcher.go
> +func (s *PrivilegedDesktopLauncher) Name() string {
This method should be renamed to `Interface`

2020-10-12 07:49 UTC, jhenstridge commented on usersession/userd/privileged_desktop_launcher.go
> +func (s *PrivilegedDesktopLauncher) BasePath() dbus.ObjectPath {
... and this one to `ObjectPath`

2020-10-12 15:35 UTC, merged

2020-10-12 15:55 UTC, AlanGriffiths commented on data/dbus/io.snapcraft.PrivilegedDesktopLauncher.service.in
> +AssumedAppArmorLabel=unconfined
Thanks @jhenstridge that works nicely